schema_version = "1.0.0"

id = "CocoDelete"
version = "2.0.0"
name = "CocoDelete"
tagline = "Delete in edit mode without the delete menu"
maintainer = "MoonCoconutz"
type = "add-on"
website = "https://github.com/MoonCoconutz/CocoTools"

tags = ["3D View", "User Interface"]

blender_version_min = "4.2.0"

license = [
  "SPDX:GPL-3.0-or-later",
]
copyright = [
  "2026 MoonCoconutz",
]

[build]
paths_exclude_pattern = [
  "/.git/",
  "__pycache__/",
  ".*",
]
